server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                # 🟢 Indiquer l'origine exacte du front-end
                allowedOrigins: "http://localhost:8084"
                # Alternative si vous voulez autoriser toutes les origines (moins sécurisé) :
                # allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
          - id: games_route
            uri: ${GAMES_SERVICE_URI}
            predicates:
              - Path=/api/games/**
          - id: collections_route
            uri: ${COLLECTION_SERVICE_URI}
            predicates:
              - Path=/api/collections/**
          - id: auth_route
            uri: ${AUTH_SERVICE_URI}
            predicates:
              - Path=/api/auth/**

