# Nom du workflow qui apparaîtra dans l'interface GitHub Actions
name: CI Multi-Service (Build & Test)

# Déclenche ce workflow sur chaque push et pull request sur la branche 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Permet d'exécuter ce workflow manuellement depuis l'interface Actions
  workflow_dispatch:
permissions:
  contents: write # Permet d'écrire des fichiers (nécessaire pour la release)
  pull-requests: write # Permet de créer et modifier des Pull Requests (critique pour release-please)

# Définition des jobs (tâches) à exécuter
jobs:
  # -----------------------------------------------------------
  # JOB 1: Build et Tests Unitaires pour les services Java (Maven)
  # -----------------------------------------------------------
  java_build:
    name: Build Services Java (Maven)
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '21'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Build and Unit Tests
        run: mvn clean install

      - name: Upload Build Artifacts (JARs)
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: |
            **/target/*.jar
            !**/target/*-sources.jar
            !**/target/*-javadoc.jar

  # -----------------------------------------------------------
  # JOB 2: Build du Frontend (Vue/Vite)
  # -----------------------------------------------------------
  frontend_build:
    name: Build Frontend (Node.js)
    runs-on: ubuntu-latest
    needs: java_build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Build (Vite)
        run: npm run build
        working-directory: ./frontend

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend/dist

  # -----------------------------------------------------------
  # JOB 3: Versioning et Création de Release (Release Please)
  # -----------------------------------------------------------
  release_and_versioning:
    name: Automated Versioning (Release Please)
    runs-on: ubuntu-latest

    # Ce job DOIT attendre que TOUS les builds et tests réussissent
    needs: [java_build, frontend_build]

    # Condition cruciale: Le versioning ne se fait que sur les pushes vers 'main'
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # CORRECTION CRITIQUE (1) : Donne au GITHUB_TOKEN la permission de déclencher d'autres workflows
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Installer l'utilitaire zip pour archiver les artefacts
      - name: Install Zip Utility
        run: sudo apt-get install zip -y

      # 1. TÉLÉCHARGER les JARs créés par le job java_build
      - name: Download Java Artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts
          path: ./java-artifacts-to-upload

      # 2. TÉLÉCHARGER le Frontend créé par le job frontend_build
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend-artifacts-to-upload

      # 3. Exécuter Release Please
      # CORRECTION CRITIQUE (2) : Passer explicitement le GITHUB_TOKEN à l'action
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }} # Assure l'autorisation complète de déclenchement

      # Les étapes suivantes ne s'exécutent que si une NOUVELLE RELEASE est créée (uniquement après un merge de PR de release)

      # 4. ZIP les artefacts (un seul fichier pour l'upload)
      - name: Zip Java Artifacts
        if: ${{ steps.release.outputs.release_created }}
        run: zip -r ./java-artifacts-to-upload/java-artifacts.zip ./java-artifacts-to-upload/

      - name: Zip Frontend Artifact
        if: ${{ steps.release.outputs.release_created }}
        run: zip -r ./frontend-artifacts-to-upload/frontend-dist.zip ./frontend-artifacts-to-upload/

      # 5. UPLOAD JAVA (Asset de Release)
      # On utilise l'URL fournie par Release Please
      - name: Upload Java Artifacts to Release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./java-artifacts-to-upload/java-artifacts.zip
          asset_name: java-artifacts-${{ steps.release.outputs.tag_name }}.zip
          asset_content_type: application/zip

      # 6. UPLOAD FRONTEND (Asset de Release)
      - name: Upload Frontend Artifact to Release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./frontend-artifacts-to-upload/frontend-dist.zip
          asset_name: frontend-dist-${{ steps.release.outputs.tag_name }}.zip
          asset_content_type: application/zip

      - name: Notify on New Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          TAG_VERSION: ${{ steps.release.outputs.tag_name }}
        run: |
          echo "Nouvelle release créée : $TAG_VERSION"
