# Nom du workflow qui apparaîtra dans l'interface GitHub Actions
name: CI Multi-Service (Build & Test)

# Déclenche ce workflow sur chaque push et pull request sur la branche 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Permet d'exécuter ce workflow manuellement depuis l'interface Actions
  workflow_dispatch:
permissions:
  contents: write # Permet d'écrire des fichiers (nécessaire pour la release)
  pull-requests: write # Permet de créer et modifier des Pull Requests (critique pour release-please)

# Définition des jobs (tâches) à exécuter
jobs:
  # -----------------------------------------------------------
  # JOB 1: Build et Tests Unitaires pour les services Java (Maven)
  # -----------------------------------------------------------
  java_build:
    name: Build Services Java (Maven)
    # Exécuter sur la dernière version d'Ubuntu
    runs-on: ubuntu-latest

    # Les variables d'environnement nécessaires
    env:
      # Utiliser Java 21 comme spécifié dans les pom.xml
      JAVA_VERSION: '21'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          # Cache les dépendances Maven pour accélérer les builds
          cache: 'maven'

      - name: Run Maven Build and Unit Tests
        # Exécute le build de tous les modules, saute les tests d'intégration, et nettoie
        run: mvn clean install

      # NOTE: Si vous avez des tests d'intégration (Testcontainers, etc.) distincts,
      # vous devrez créer un profil Maven spécifique et un step dédié.

      - name: Upload Build Artifacts (JARs)
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          # Sauvegarde tous les fichiers JAR générés par les modules
          path: |
            **/target/*.jar
            !**/target/*-sources.jar
            !**/target/*-javadoc.jar

  # -----------------------------------------------------------
  # JOB 2: Build du Frontend (Vue/Vite)
  # -----------------------------------------------------------
  frontend_build:
    name: Build Frontend (Node.js)
    runs-on: ubuntu-latest
    # Le frontend ne doit s'exécuter que si le build Java a réussi
    needs: java_build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Cache les dépendances Node.js (node_modules)
          cache: 'npm'
          # Chemin vers package-lock.json pour le cache
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        # Va dans le dossier frontend et installe les dépendances
        run: npm install
        working-directory: ./frontend

      - name: Run Frontend Build (Vite)
        # Exécute la commande de build Vite
        run: npm run build
        working-directory: ./frontend

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          # Le dossier de sortie du build Vite
          path: ./frontend/dist

  # -----------------------------------------------------------
  # JOB 3: Versioning et Création de Release (Release Please)
  # -----------------------------------------------------------
  release_and_versioning:
    name: Automated Versioning (Release Please)
    runs-on: ubuntu-latest

    # Ce job DOIT attendre que TOUS les builds et tests réussissent
    needs: [java_build, frontend_build]

    # Condition cruciale: Le versioning ne se fait que sur les pushes vers 'main'
    # et PAS sur les Pull Requests.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. TÉLÉCHARGER les JARs créés par le job java_build
      - name: Download Java Artifacts (JARs)
        uses: actions/download-artifact@v4
        with:
          name: java-artifacts
          # Les JARs seront téléchargés dans ce dossier
          path: ./java-artifacts-to-upload

      # 2. TÉLÉCHARGER les fichiers frontend
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./frontend-artifacts-to-upload

      # 3. Exécuter Release Please pour créer le tag et la PR de release
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

      # 4. ZIP les artefacts (NÉCESSAIRE pour l'upload d'assets de release)
      - name: Zip Artifacts (Required for Upload)
        # S'exécute uniquement si une nouvelle release a été créée
        if: ${{ steps.release.outputs.release_created }}
        run: |
          # Installation de zip
          sudo apt-get install zip -y
          
          # Créer l'archive Zip des JARs
          # Le chemin doit être ./java-artifacts-to-upload/*.jar pour ne pas zipper le dossier lui-même
          zip -r ./java-artifacts-to-upload/java-artifacts.zip ./java-artifacts-to-upload/* # Créer l'archive Zip du Frontend
          zip -r ./frontend-artifacts-to-upload/frontend-dist.zip ./frontend-artifacts-to-upload/*

      # 5. UPLOAD JAVA (Asset de Release)
      - name: Upload Java Artifacts to Release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./java-artifacts-to-upload/java-artifacts.zip
          asset_name: java-artifacts-${{ steps.release.outputs.tag_name }}.zip
          asset_content_type: application/zip

      # 6. UPLOAD FRONTEND (Asset de Release)
      - name: Upload Frontend Artifact to Release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./frontend-artifacts-to-upload/frontend-dist.zip
          asset_name: frontend-dist-${{ steps.release.outputs.tag_name }}.zip
          asset_content_type: application/zip

      - name: Notify on New Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          TAG_VERSION: ${{ steps.release.outputs.tag_name }}
        run: |
          echo "Nouvelle release créée : $TAG_VERSION"
          # NOTE: C'est à ce moment que le workflow de DEPLOIEMENT (cd_docker_deploy.yml) est déclenché
