# Nom du workflow qui apparaîtra dans l'interface GitHub Actions
name: 1. Automated Versioning (Release Please)

# Déclenche ce workflow sur chaque push sur la branche 'main'
on:
  push:
    branches:
      - main

# Permissions pour permettre à release-please de créer des PR et des Tags
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

      - name: Notify on New Release
        # Ce step s'exécute uniquement si une nouvelle release a été créée par l'action précédente
        if: ${{ steps.release.outputs.release_created }}

        env:
          TAG_VERSION: ${{ steps.release.outputs.tag_name }}

        run: |
          echo "Nouvelle release créée : $TAG_VERSION"
